CREATE TABLE IF NOT EXISTS driver_availability (
    user_id BIGINT PRIMARY KEY,
    available BOOLEAN NOT NULL DEFAULT FALSE,
    latitude DECIMAL(10, 6) NOT NULL DEFAULT 0,
    longitude DECIMAL(10, 6) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
